apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-db-app
  namespace: {{NAMESPACE}}
spec:
  selector:
    matchLabels:
      app: analysis-db-app
  replicas: 1
  template:
    metadata:
      labels:
        app: analysis-db-app
    spec:
      containers:
        - name: postgres
          image: postgres:12
          ports:
            - name: db-port
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: analysis
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: analysis-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analysis-db-credentials
                  key: password
          volumeMounts:
            - name: analysis-db-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: analysis-db-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: analysis-db
  name: analysis-db
  namespace: {{NAMESPACE}}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      targetPort: db-port
  selector:
    app: analysis-db-app