apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-app
  namespace: {{NAMESPACE}}
spec:
  selector:
    matchLabels:
      app: analysis-app
  replicas: 1
  template:
    metadata:
      labels:
        app: analysis-app
    spec:
      containers:
        - name: analysis-container
          image: {{IMAGE_NAME}}
          imagePullPolicy: Always
          ports:
            - name: app-port
              containerPort: 8080
              protocol: TCP
          env:
            - name: KUMULUZEE_VERSION
              value: {{VERSION}}
            - name: KUMULUZEE_ENV_NAME
              value: {{ENV_NAME}}
            - name: KUMULUZEE_ENV_PROD
              value: "{{ENV_PROD}}"
            - name: KUMULUZEE_GRPC_CLIENTS0_ADDRESS
              value: sequence-bank-app
            - name: KUMULUZEE_GRPC_CLIENTS0_PORT
              value: "8081"
          livenessProbe:
            httpGet:
              path: /health/live
              port: app-port
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: app-port
            initialDelaySeconds: 30
            periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: analysis-service
  namespace: {{NAMESPACE}}
  labels:
    app: analysis-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: app-port
      name: rest
  selector:
    app: analysis-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: analysis
  namespace: {{NAMESPACE}}
spec:
  rules:
    - host: analysis{{ENV_SUFFIX}}.mydna.codes
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: analysis-service
                port:
                  number: 8080