kumuluzee:
  name: analysis
  version: 1.0.0-SNAPSHOT
  env:
    prod: false
    name: dev
  dev:
    scan-libraries:
      - rest-lib
      - analysis-lib
  server:
    base-url: http://localhost:8080
    show-server-info: false
    http:
      port: 8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST"
      exposed-headers: "X-Total-Count, Content-Type"
  grpc:
    clients:
      - name: sequence-bank-grpc-client
        port: 8081
        address: localhost
      - name: analysis-result-grpc-client
        port: 8082
        address: localhost
  graphql:
    mapping: /graphql
    ui:
      mapping: /graphiql
      enabled: true
    schema:
      base-packages:
        - codes.mydna.lib
#  streaming:
#    kafka:
#      producer:
#        bootstrap-servers: localhost:9091
#        acks: all
#        retries: 0
#        batch-size: 16384
#        linger-ms: 1
#        buffer-memory: 33554432
#        key-serializer: org.apache.kafka.common.serialization.StringSerializer
#        value-serializer: org.apache.kafka.common.serialization.StringSerializer

keycloak:
  realm: not_set
  auth-server-url: not_set
  client-id: not_set
  auth:
    client-secret: not_set