kumuluzee:
  name: analysis
  version: 1.0.0-SNAPSHOT
  env:
    prod: false
    name: dev
  server:
    show-server-info: false
    base-url: http://localhost:8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count"
  openapi:
    enabled: true
    ui:
      enabled: true
  health:
    servlet:
      mapping: /health/
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/analysis-db
      disk-space-health-check:
        threshold: 100000000
        type: liveness
  datasources:
    - jndi-name: jdbc/analysis-db
      connection-url: jdbc:postgresql://localhost:5432/analysis
      username: postgres
      password: postgres
      pool:
        max-size: 20