kumuluzee:
  name: analysis
  version: 1.0.0-SNAPSHOT
  env:
    prod: false
    name: dev
  server:
    base-url: http://localhost:8080
    show-server-info: false
    http:
      port: 8090
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count"
  openapi-mp:
    enabled: true
    servers: http://localhost:8080
    ui:
      enabled: true
  health:
    servlet:
      mapping: /health/
      enabled: true
  grpc:
    clients:
      - name: sequence-bank-grpc-client
        port: 8081
        address: localhost
  graphql:
    mapping: /graphql
    ui:
      mapping: /graphiql
      enabled: true
    schema:
      base-packages:
        - codes.mydna.lib